.\" Manpage for pgpooler.
.\" Contact contact@nslab.at.
.TH man 8 "16.02.2018" "1.0.0" "pgpooler man page"
.SH NAME
pgpooler \- is a tool that supports pgpool management.
.SH SYNOPSIS
pgpooler <option|long-option>
.SH DESCRIPTION
Pgpooler is a tool that supports pgpool management.
.SH OPTIONS
--help
        show this message
.SH SEE ALSO
https://github.com/trimstray/pgpooler
.SH BUGS
No known bugs.
.SH AUTHOR
trimstray (contact@nslab.at)
